language: php
sudo: false

php:
  - 7.2
  - 7.4
  - 8.0
  - 8.1

before_script:
  - composer self-update
  - composer install --no-interaction

notifications:
  email: false

script:
  - vendor/bin/phpunit
